booktrack/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('track.urls')),
    # url(r'^books/', include('track.urls')),
    url(r'^admin/', admin.site.urls),
]

track/urls.py
from django.conf.urls import url

from . import views
from track.views import AddBook, SignIn, SignUp, BoardSettings

app_name = 'track'
urlpatterns = [
	url(r'^$', views.landing_page, name='main'),
	url(r'^signin/$', SignIn.as_view(), name='signin'),
	url(r'^signout/$', views.signout, name='signout'),
	url(r'^register/$', SignUp.as_view(), name='register'),
    url(r'^user/(?P<user_id>[0-9]+)/$', views.index, name='index'),
    url(r'^add/$', AddBook.as_view(), name='create_book'),
    url(r'^user/(?P<user_id>[0-9]+)/user_profile/$', BoardSettings.as_view(), name='change_settings'),
    url(r'^change_status/$', views.change_status, name='change_status'),
    url(r'^delete_book/(?P<book_id>[0-9]+)/$', views.delete_book, name='delete_book'),
    # url(r'^change_status/(?P<book_id>[0-9]+)$', views.change_status, name='change_status'),
    # url(r'^(?P<status_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^add/$', views.add, name='add'),
    url(r'^(?P<book_id>[0-9]+)/about/$', views.details, name='details')
]

track/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

"""
DB structure:

Tables:

1. BOOK [id, title, author, year, language_id (FK), genre_id(FK), user_id (FK), status_id (FK), date_created, date_modified]
2. Status [id, status_text]
3. Language [id, language]
4. Genre [id, genre]
5. Settings [id, book_amount, show_board, show_cover, user (FK)]
6. User (default django table)

"""


class Settings(models.Model):

    """
    Class for making a table Settings in DB with a 'user' foreign key
    """

    books_amount = models.CharField(max_length=20, default=10)
    show_board = models.BooleanField(default=False)
    show_cover = models.BooleanField(default=False)
    # The table is connected with auth_user table
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        settings = "{},{},{}".format(str(self.books_amount), str(self.show_board), str(self.show_cover))
        return settings


class Status(models.Model):

    """
    Class for making a table Status in DB.
    So far five statuses are in the table:
    Book To Read, Currently Reading, Read, Archived, Deleted
    The table is populated with the help of '/utils/populate_database.py' script
    """

    status_text = models.CharField(max_length=100)

    def __str__(self):
        return self.status_text


class Language(models.Model):

    """
    Class for making a table Language in DB.
    So far 16 languages are in the table.
    To populate the table with other languages
    you may use this script '/utils/populate_database.py'
    """

    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Genre(models.Model):

    """
    Class for making a table Genre in DB.
    So far 16 genres are in the table.
    To populate the table with other genres
    you may use this script '/utils/populate_database.py'
    """

    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.genre


class Book(models.Model):

    """
    The main table in DB.
    All the books and their properties are stored here.
    Fields 'year' and 'genre' can have null values as these
    parameters are not important for book processing
    """
   
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    year = models.CharField(max_length=200, null=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_pub_created = models.DateTimeField('date published', editable=False, null=True)
    date_pub_modified = models.DateTimeField('date published')

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''

        # if the book does not exist
        # add date_pub_created field
        # else: add date_pub_modified field
        if not self.id:
            self.date_pub_created = timezone.now()
        self.date_pub_modified = timezone.now()
        return super(Book, self).save(*args, **kwargs)

    def __str__(self):
        book_string = "{}, {}, {}, {}".format(self.title, self.author, self.genre, self.language)
        return book_string

track/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http import QueryDict
from django.contrib import auth
from django.db import IntegrityError

from .models import Status, Book, Language, Genre, Settings

from .utils.search_book_info import get_book_info
from .utils.search_for_author import get_author_info


class SignUp(View):

    """
    Class handling the process of user registration.

    With 'get' method it shows an html-template with
    a registration form.
    With 'post' method it receives user's credentials
    and stores them in auth_user table.
    """

    def get(self, request, *args, **kwargs):

        """ On response show a web-page with a registration form"""

        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('track:index',
                                                args=(request.user.id,)))
        else:
            return render(request, 'track/registration.html')

    def post(self, request, *args, **kwargs):

        """
        Get user's credentials.

        Check if email is unique.
        If unique, create a user with given credentials
        and redirect him/her to the board.

        """

        username = request.POST.get("username").strip()
        email = request.POST.get("email").strip()
        password = request.POST.get("password").strip()
        password2 = request.POST.get("password2").strip()

        if password == password2:

            if email and User.objects.filter(email=email).exclude(username=username).count():
                return HttpResponse("User with this email already exists")

            else:

                try:
                    user = User.objects.create_user(username=username, email=email, password=password)
                except IntegrityError:
                    return HttpResponse("User with this name already exists")
                except ValueError:
                    return HttpResponse("You should fill in all the fields in the registration form")
                else:

                    user.save()
                    user = auth.authenticate(username=username, password=password)

                    user.settings_set.create()
                    auth.login(request, user)

                    return HttpResponseRedirect(reverse('track:index',
                                                        args=(user.id,)))
        else:
            return HttpResponse("Password confirmation is incorrect! Try again")


class SignIn(View):

    """
    Class handling the process of user login.

    With 'get' method it shows a web-page with a login form.
    With 'post' method it receives user's credentials.
    If user exists (user's email in DB), authenticate him/her,
    check if user is active --> login user and redirect him/her
    to the board.
    """

    def get(self, request, *args, **kwargs):
        
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('track:index',
                                                args=(request.user.id,)))

        else:
            template = 'track/login.html'
            return render(request, template)

    def post(self, request, *args, **kwargs):

        email = request.POST.get("email").strip()
        password = request.POST.get("password").strip()
        
        try:
            username = User.objects.get(email=email)
        except User.DoesNotExist:
            return HttpResponse("User with this email does not exist")

        else:

            user = auth.authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('track:index',
                                                        args=(user.id,)))
                else:
                    return HttpResponse("Your password is valid, but the account was disabled, \
											please contact administrator.")
            else:
                return HttpResponse("Password is incorrect.")


def signout(request):

    """ 
    The function uses built-in django method
    to logout the user.
    After logging out it redirects to main page.

    """

    auth.logout(request)

    return HttpResponseRedirect(reverse('track:main'))


def landing_page(request):

    """
    The function shows the main web-page.
    If a user is authenticated, it redirects
    him/her to the books board.
    Otherwise it suggests to sign up/in.
    """

    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('track:index', args=(request.user.id,)))

    else:

        template = 'track/main.html'
        return render(request, template)


def index(request, user_id):

    """
    The function shows the books board.
    First it tries to load a user setting (show my board to others).
    Then it checks if the id of the user in session is not equal to
    the id of a requested board and if the setting is set to False,
    it restricts the user to see the board.
    Otherwise it shows the board.
    """

    try:
        sh_board = Settings.objects.get(user_id=user_id).show_board

    except Settings.DoesNotExist:

        response = "User with an ID: {} is not found".format(user_id)
        return HttpResponse(response)

    if int(user_id) != request.user.id and sh_board == False:

        return HttpResponse("This user has forbidden to see his/her board. Return to your page.")

    else:

        template = 'track/base.html'
        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            response = "User with an ID: {} is not found".format(user_id)
            return HttpResponse(response)

        else:
            # getting user's books and statuses
            books = user.book_set.order_by('-date_pub_modified')
            status_list = Status.objects.all()

            # making an empty dictionary, where keys are statuses
            # and values are books
            books_list = {status: [] for status in status_list}

            # adding books to statuses according to
            # the status, assigned to each book.
            for book in books:
                if book.status in status_list:
                    books_list[book.status].append(book)

                else:
                    response = "Can't find the status for book '{}'".format(book.title)
                    return HttpResponse(response)

            # removing Deleted column,
            # in order not to show it on the board
            status_to_delete = Status.objects.all().filter(status_text="Deleted")[0]
            books_list.pop(status_to_delete)

            context = {'status_list': status_list, 'books_list': books_list, 'user_id': int(user_id)}

            return render(request, template, context)


class AddBook(View):

    """
    Class handling the process of adding a new book
    to the DB.
    The 'get' method shows the form for adding a book.
    The 'post' method get book data from form fields
    and inserts it into the DB and redirects to the board
    where the added book appears in the Books To Read column.

    """

    def get(self, request, *args, **kwargs):

        # select all languages from Language table
        language_list = Language.objects.all()
        # select all genres from Genre table
        genre_list = Genre.objects.all()

        template = 'track/add_book.html'
        context = {'language_list': language_list, 'genre_list': genre_list}

        return render(request, template, context)

    def post(self, request, status_id=1, *args, **kwargs):

        # setting status_id to 1 since we can add books
        # only with the status 'Books To Read'.
        status = Status.objects.get(pk=status_id)

        title = request.POST['title'].strip()
        author = request.POST['author'].strip()
        year = request.POST['year'].strip()
        language_id = request.POST.get('language')
        genre_id = request.POST.get('genre')

        book = status.book_set.create(
            title=title, author=author,
            year=year, language_id=language_id,
            genre_id=genre_id, user_id=request.user.id
        )
        book.save()

        return HttpResponseRedirect(reverse('track:index', args=(request.user.id,)))


class BoardSettings(View):

    """
    Class handles the process of setting and changing
    user settings. During a new user creation these settings
    are added by default. Later a user can change them.

    So far only one setting is configurable - show board to others.
    """

    def get(self, request, *args, **kwargs):

        template = 'track/board_settings.html'
        bks_amount = Settings.objects.get(user_id=request.user.id).books_amount
        sh_board = Settings.objects.get(user_id=request.user.id).show_board
        sh_cover = Settings.objects.get(user_id=request.user.id).show_cover

        
        # showing some statistics about genres
        # in the user profile.
        if request.user.book_set.all():
            genres = Genre.objects.all()

            fav_genres = []

            for genre in genres:
                g_count = request.user.book_set.filter(genre__genre="{}".format(genre)).count()
                fav_genres.append((genre, g_count))

            fav_genres_sorted = sorted(((g, c) for g, c in fav_genres), key=lambda g: g[1], reverse=True)
            fav_genres = [(gen, count) for gen, count in fav_genres_sorted if count > 1][:3]
        else:
            fav_genres = []


        context = {
            'books_amount': bks_amount, 'show_board': sh_board,

track/templates/track/base.html
<!doctype html>
<html>
    <head>
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MyBooksTracker</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% load staticfiles %}
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
  {% if request.user.id == user_id %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  {% endif %}
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'track/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'track/dist/css/skins/_all-skins.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
	<style>
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 550px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* On small screens, set height to 'auto' for the grid */
    @media screen and (max-width: 767px) {
      .row.content {height: auto;}
    }

	.tilt {
    transform: rotate(3deg);
    -moz-transform: rotate(3deg);
    -webkit-transform: rotate(3deg);
  }

  .column {

  }

  .version {
  color:white;
  }

  .book-cover {
	height:50%;
	width:100%;
    background-image:url({% static 'track/images/book_cover1_smaller2.png' %});
    background-size: contain;
    background-repeat: no-repeat;
	background-position: center;
  }

  p {
    font-size: 0.900em;
	}


	</style>

<script type="text/javascript">

	$(onPageLoad);

  function onPageLoad()
  {
    $( ".column" ).sortable({
      connectWith: ".column",
      handle: ".header, .content1",
	  containment: ".container-fluid",
	  cursor: "move",
	  delay: 50,
	  opacity: 0.7,
	  revert: 350,
	  tolerance: "pointer",
	  helper:'clone',
      scroll: true,
      start: function (event, ui) {
        ui.item.addClass('tilt');
      },
      stop: function (event, ui) {
        ui.item.removeClass('tilt');
      },
	  change: function (event, ui){
		var book_id = ui.item.attr("id");
		var status_id = event.target.id;
		var ids = { s_id : status_id, b_id : book_id }

		$.ajax({
		  url: "{% url 'track:change_status' %}",
		  method: "POST",
		  data: ids,
		  contentType: 'application/x-www-form-urlencoded; charset=utf-8',
		  processData: true,
		  });
	  },
	  receive: function (event, ui){
		var book_id = ui.item.attr("id");
		var status_id = event.target.id;
		var ids = { s_id : status_id, b_id : book_id }

		$.ajax({
		  url: "{% url 'track:change_status' %}",
		  method: "POST",
		  data: ids,
		  contentType: 'application/x-www-form-urlencoded; charset=utf-8',
		  processData: true,
		  });
	  }
    });
  }

</script>
</head>

<body class="hold-transition skin-blue layout-top-nav">

{% if user.is_authenticated %}
<div class="wrapper">

  <header class="main-header">
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header" style="padding:5px 0px 0px 0px">
          <a href="{% url 'track:main' %}" class="navbar-brand">MyBooks<b>Tracker</b></a>
		  <a class="w3-btn btn btn-warning" href="{% url 'track:create_book' %}" style="padding:10px 5px 10px 5px;border-radius: 0 !important;"  role="button">Add a new book</a>
        </div>

        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">

            <!-- User Account Menu -->
            <li class="dropdown user user-menu">
              <!-- Menu Toggle Button -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- The user image in the navbar-->
                <img src="{% static 'track/images/avatar.png' %}" class="user-image" alt="User Image">
                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                <span class="hidden-xs">Welcome, {{ user.username }}!</span>
              </a>
              <ul class="dropdown-menu">
                <!-- The user image in the menu -->
                <li class="user-header">
                  <img src="{% static 'track/images/avatar.png' %}" class="img-circle" alt="User Image">

                  <p>
                    {{ user.username }}
                    <small>Member since {{user.date_joined|date:"d M Y"}}</small>
                  </p>
                </li>
                <!-- Menu Body -->

                <!-- Menu Footer-->
                <div class="row">
				  <div  class="col-sm-4">
                    <a href="{% url 'track:change_settings' user.id %}" class="btn btn-default btn-flat">User Profile</a>
                  </div>
                  <div  class="col-sm-4">
                    <a href="{% url 'track:signout' %}" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </div>
				<div class="row"></div>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-custom-menu -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </header>

  {% if books_list %}
<div class="container-fluid content-wrapper" style="height:99%">
	<div class="container" style="height:100%;">

		<!-- Content Header (Page header) -->
	  <section class="content-header">

		<h1>
		  Books Board
		  <small>Version 0.1</small>
		</h1>
		<ol class="breadcrumb">
		  <li><a href="#">Home</a></li>
		  <li><a href="#">Books Board</a></li>
		</ol>

	  </section>

	<!-- Main content -->
    <section class="content" style="height:85%;overflow:auto;">
	<div class="row" style="height:99%;">

	{% for status, books in books_list.items %}
		<div class="col-md-{% widthratio 12 books_list|length 1 %}" style="height:100%;padding:0 10px 0 0">
            {% if status.id == 1 %}
			<div class="box box-solid box-warning" style="height:100%;">
			{% elif status.id == 2 %}
			<div class="box box-solid box-success" style="height:100%;">
			{% elif status.id == 3 %}
			<div class="box box-solid box-primary" style="height:100%;">
			{% elif status.id == 4 %}
			<div class="box box-solid box-default" style="height:100%;">
			{% endif %}
			  <div class="box-header with-border">
				<h3 class="box-title">({{ books|length }}) {{ status.status_text }}</h3>

			  </div><!-- /.box-header -->
			  <div class="box-body column sortable" id="status_{{status.id}}" style="height:90%;overflow-y:scroll;overflow-x:hidden;">
				{% if books|length == 0 %}
					{% if status.id == 1%}
					<p>Click Add a new book button to start using the board</p>
					{% else %}
					<p>Drag&Drop a book here to change its status</p>
					{% endif %}
				{% endif %}

				{% for book in books %}

				<!-- <div class="" style="width:100%;"> -->
				<div class="" style="text-align:center;" id="book_{{book.id}}">

					<div class="row" >
					<div class="col-sm-1"></div>

					<div class="well col-sm-8" style="background-color:#e2e6e9;box-shadow: 10px 5px 5px #b3b3b3;">


					<div class="header" ><p>{{ book.author }}</p></div>


					<div class="content1"><p style="align:center"><b><a href="{% url 'track:details' book.id %}">{{ book.title }}</a></b></p><br/><br/>

					<p>{{ book.year }}</p>

					</div>

					</div>
					{% if request.user.id == user_id %}
					<div class="col-sm-2">
					<p><a href="{% url 'track:delete_book' book.id %}" class="btn btn-default" role="button">x</a></p>
					</div>
					{% endif %}

					</div>

				</div>
				<!-- </div> -->

				{% endfor %}

			  </div>
			  <!-- /.box-body -->
			</div>
			<!-- /.box -->

		</div>
	{% endfor %}
	</div>
	</section>
      <!-- /.content -->

	</div> <!-- /.container -->
  {% else %}
    <p>You haven't add any books yet.</p>
  {% endif %}

</div> <!-- /.container-fluid -->

<footer class="main-footer">
    <div class="container">

      <strong>Copyright &copy; </strong> All rights reserved.
    </div>
    <!-- /.container -->
  </footer>

{% else %}
	<div>You should be logged in to view your books</div>
    <div><p><a href="{% url 'track:register' %}">Register</a></p><p><a href="{% url 'track:signin' %}">Login</a></p></div>
{% endif %}
</div> <!-- End Wrapper-->

<!-- SlimScroll -->
<script src="{% static 'track/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'track/plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'track/dist/js/app.min.js' %}"></script>


</body>

</html>

track/templates/track/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sign in to MyBookTracker</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'track/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'track/dist/css/skins/_all-skins.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="container-fluid">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'track:main' %}"><b>MyBook</b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start see your books board</p>
	
	<form class="form" role='form' enctype="multipart/form-data" method="post" name='signin_form' data-toggle="validator">
	{% csrf_token %}
	<div class="form-group has-feedback">
		<input type="email" class="form-control" id="email" name="email" placeholder="Email" pattern='^(([^<>()\[\]\\.,;:\s@\"]+(\.[^<>()\[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$' data-error="Enter a valid email" autofocus required>
		<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
		<div class="help-block with-errors"></div>
	  </div>
	  <div class="form-group has-feedback">
		<span class="glyphicon glyphicon-lock form-control-feedback"></span>
		<input type="password" class="form-control" id="password" name="password" placeholder="Password" data-error="You forgot about the password" autofocus required>
		<div class="help-block with-errors"></div>
	  </div>
	<div class="form-group has-feedback">  
	<input class="w3-btn btn-warning btn-block btn-flat" type="submit" value="Sign in"/>
	</div>
	</form>

    New to MyBookTracker? <a class="text-center" href="{% url 'track:register' %}">Register a new account</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
</div>

<script src="{% static 'track/dist/js/validator.min.js' %}"></script>
</body>
</html>

track/templates/track/main.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>BOOKTRACK</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<style>
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 550px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
        
    /* On small screens, set height to 'auto' for the grid */
    @media screen and (max-width: 767px) {
      .row.content {height: auto;} 
    }
	
	.tilt {
    transform: rotate(3deg);
    -moz-transform: rotate(3deg);
    -webkit-transform: rotate(3deg);
  }

  .column {
    
  }

	</style>
	

	</head>
<body>
<br/>

<div class="container-fluid">

	<p>Welcome user! Please, <a href="{% url 'track:register' %}">sign up</a> and start tracking your books!</p>
	<p>Already have an account? <a href="{% url 'track:signin' %}">Sing in</a>, then!</p>

</div>

</body>

</html>